[tools]
'cargo:askama_fmt' = '0.4.0'
'cargo:sqlx-cli' = '0.9.0'
node = '24.18.0'
rust = '1.97.1'
rust-analyzer = '2026-07-27'
watchexec = '2.5.1'
pnpm = '11.18.0'

[env]
_.file = ['.env', '.env.local']

[tasks.dev]
description = 'Run the server'
run = '''
exec watchexec --restart \
  --watch apps/server/src \
  --watch templates/ \
  --watch Cargo.toml \
  --exts rs,html,toml \
  -- cargo run -p server --bin server
'''

[tasks.lint]
description = 'Run Clippy'
run = 'cargo clippy --all-targets --all-features -- -D warnings'
