[tools]
"cargo:bacon" = "latest"
"cargo:sqlx-cli" = "latest"
"github:nats-io/nats-server" = "latest"
"github:nats-io/natscli" = "latest"
rust = "1.96.0"
rust-analyzer = "latest"
watchexec = "latest"

[env]
_.file = [".env", ".env.local"]

[tasks."dev:nats"]
run = "nats-server -js -sd ./.data/nats"

[tasks."dev:server"]
run = "watchexec -r -e rs,html -- cargo run"

[tasks.dev]
depends = ["dev:nats", "dev:server"]

[tasks."db:up"]
run = "docker compose up -d db"

[tasks."db:down"]
run = "docker compose down db"

[tasks."db:prompt"]
run = "docker compose exec db psql -U postgres -d app_db"

[tasks."db:migrate"]
run = "sqlx migrate run"
